### PR TITLE
Add Angstrom

### PR DESCRIPTION
**Pull request by giordano**
[Angstrom](https://en.wikipedia.org/wiki/%C3%85ngstr%C3%B6m) is quite common in astronomy, may be useful in this package.

### CODE REVIEW

**Comment by mweastwood** [comment]
Yup, I agree. This is an important unit to have.

The `10^10` makes me a little nervous because that will overflow on 32-bit systems. In general I think forced promotion to `Float64` is a lesser evil to integer-overflow which is why I have usually tended to favor floating point conversion constants here. I'm not sure what the right balance is. Do you have any strong opinions?

**Comment by giordano** [comment]
Yes, good point about overflow. Indeed it's a tough decision, and I agree that a Float64 constant is better than guaranteed overflow. I'll update the patch tomorrow.

PS I cannot use the syntax u"A" (with the ring on it), is it expected?

PPS if you had enabled appveyor for this repository,  you have to update the settings to point to the new address

**Comment by mweastwood** [comment]
The `u"foo"` syntax is really just looking for a symbol named `foo` in any module registered with Unitful. I believe if you add a line like `const Å = angstrom` after the unit definition, the `u"Å"` syntax should work. As you have it right now, `u"angstrom"` should work.

I didn't have appveyor enabled yet. I've been waiting for a little chunk of free time before attempting that because I haven't used it before.

**Comment by giordano** [comment]
> The `u"foo"` syntax is really just looking for a symbol named `foo` in any module registered with Unitful. I believe if you add a line like `const Å = angstrom` after the unit definition, the `u"Å"` syntax should work. As you have it right now, `u"angstrom"` should work.

Oops, I misunderstood the meaning of the first two arguments of `@unit`, I thought the symbol used was the second argument.

I don't have a strong opinion on this, but maybe `Å` is better as unit, being the real unit symbol?  The only problem is that it isn't a character that can be found on the keyboard.  For example, I never understood how to use LaTeX commands in Jupyter, like it works in the REPL.

**Comment by mweastwood** [comment]
I think it's fair to have a non-unicode alias for every unicode symbol. This looks good for now although I might think about adding `const Å = angstrom` at some point to appease the unicode-lovers out there.

**Pull request merged**
