### PR TITLE
Magnitude Calculations

### PR DESCRIPTION
**Pull request by mileslucas**
Starting with #12 I went over to Unitful and they resolved the issue ([#265](https://github.com/PainterQubits/Unitful.jl/issues/265) and [#267](https://github.com/PainterQubits/Unitful.jl/pull/267)). For now, I've updated `project.toml` to use the master branch of unitful. We should keep an eye on a release and pin that first release here.

I've also added some tests to verify the code works as intended (also mirrored in the tests over at Unitful.jl).

### CODE REVIEW

**Comment by mileslucas** [comment]
I realize now there is no way to pin a version to a git branch, so I guess this will have to wait until Unitful updates its version.

**Comment by ajkeller34** [comment]
in progress: https://github.com/PainterQubits/Unitful.jl/commit/5bdf76e855d18f92c23f67c3d8553e02123072a0

**Comment by mileslucas** [comment]
Thanks @ajkeller34!

This should be ready to merge pending any review @giordano

**Review by giordano — APPROVED** [review]
It looks ok, but let's wait for Unitful 0.17 to be released and run CI again.

**Pull request merged**
